import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict
from typing import List
from typing import Optional


@dataclass
class SemanticTag:
    """
    Semantic tag extracted from annotated source code.
    """

    tag: str
    line: int
    column: int = 1


@dataclass
class DebugInstruction:
    """
    LLVM instruction debug information.

    Exported from LLVM/KLEE side.
    """

    inst_id: int
    bb_id: int
    line: int
    column: int


@dataclass
class TagBinding:
    """
    Final mapping result.

    tag -> basic block
    """

    tag: str
    bb_id: int


class TagBindingError(Exception):
    pass


def load_tags(
    tag_json_path: str,
) -> List[SemanticTag]:
    """
    Load semantic tags generated by tag_creation.py.

    Expected format:

    {
      "function":"parse_box",
      "tags":[
        {
          "tag":"MOOV_PROCESSING",
          "line":123,
          "column":1
        }
      ]
    }
    """

    data = json.loads(
        Path(tag_json_path).read_text(
            encoding="utf-8"
        )
    )

    result = []

    for item in data["tags"]:
        result.append(
            SemanticTag(
                tag=item["tag"],
                line=item["line"],
                column=item.get("column", 1),
            )
        )

    return result


def load_debug_info(
    debug_json_path: str,
) -> List[DebugInstruction]:
    """
    Load LLVM debug information.

    Expected format:

    [
      {
        "inst_id":1,
        "bb_id":10,
        "line":100,
        "column":5
      }
    ]
    """

    data = json.loads(
        Path(debug_json_path).read_text(
            encoding="utf-8"
        )
    )

    result = []

    for item in data:
        result.append(
            DebugInstruction(
                inst_id=item["inst_id"],
                bb_id=item["bb_id"],
                line=item["line"],
                column=item["column"],
            )
        )

    return result


def before(
    inst: DebugInstruction,
    line: int,
    column: int,
) -> bool:
    """
    Whether instruction location
    appears before tag location.
    """

    if inst.line < line:
        return True

    if inst.line == line:
        return inst.column < column

    return False


def after(
    inst: DebugInstruction,
    line: int,
    column: int,
) -> bool:
    """
    Whether instruction location
    appears after tag location.
    """

    if inst.line > line:
        return True

    if inst.line == line:
        return inst.column > column

    return False


def find_anchor_before(
    tag: SemanticTag,
    instructions: List[DebugInstruction],
) -> Optional[DebugInstruction]:
    """
    Paper:

    Last instruction preceding tag location.
    """

    candidates = []

    for inst in instructions:

        if before(
            inst,
            tag.line,
            tag.column,
        ):
            candidates.append(inst)

    if not candidates:
        return None

    candidates.sort(
        key=lambda x: (
            x.line,
            x.column,
        )
    )

    return candidates[-1]


def find_anchor_after(
    tag: SemanticTag,
    instructions: List[DebugInstruction],
) -> Optional[DebugInstruction]:
    """
    Paper:

    First instruction following tag location.
    """

    candidates = []

    for inst in instructions:

        if after(
            inst,
            tag.line,
            tag.column,
        ):
            candidates.append(inst)

    if not candidates:
        return None

    candidates.sort(
        key=lambda x: (
            x.line,
            x.column,
        )
    )

    return candidates[0]


def bind_single_tag(
    tag: SemanticTag,
    instructions: List[DebugInstruction],
) -> TagBinding:
    """
    Paper E.b:

    If both anchor instructions belong
    to the same basic block:

        tag -> current basic block

    Otherwise:

        tag -> successor block

    Successor block is approximated by
    the block containing the first
    instruction after the tag.
    """

    before_inst = find_anchor_before(
        tag,
        instructions,
    )

    after_inst = find_anchor_after(
        tag,
        instructions,
    )

    if before_inst is None:
        raise TagBindingError(
            f"No anchor-before instruction for tag {tag.tag}"
        )

    if after_inst is None:
        raise TagBindingError(
            f"No anchor-after instruction for tag {tag.tag}"
        )

    if before_inst.bb_id == after_inst.bb_id:

        target_bb = before_inst.bb_id

    else:

        target_bb = after_inst.bb_id

    return TagBinding(
        tag=tag.tag,
        bb_id=target_bb,
    )


def merge_tags(
    bindings: List[TagBinding],
) -> Dict[int, str]:
    """
    Paper:

    Multiple tags associated with the
    same basic block are merged into
    a single composite tag.
    """

    bb_to_tags = {}

    for binding in bindings:

        bb_to_tags.setdefault(
            binding.bb_id,
            []
        )

        bb_to_tags[
            binding.bb_id
        ].append(
            binding.tag
        )

    result = {}

    for bb_id, tags in bb_to_tags.items():

        if len(tags) == 1:

            result[bb_id] = tags[0]

        else:

            result[bb_id] = " | ".join(tags)

    return result


def build_tagging_function(
    tags: List[SemanticTag],
    instructions: List[DebugInstruction],
) -> Dict[int, str]:
    """
    Construct semantic tagging function:

        T_f : BasicBlock -> SemanticTag
    """

    bindings = []

    for tag in tags:

        bindings.append(
            bind_single_tag(
                tag,
                instructions,
            )
        )

    return merge_tags(
        bindings
    )


def bind_tags(
    tag_json_path: str,
    debug_json_path: str,
) -> Dict[int, str]:
    """
    Complete workflow.

    Returns:

        {
            bb_id: semantic_tag
        }
    """

    tags = load_tags(
        tag_json_path
    )

    instructions = load_debug_info(
        debug_json_path
    )

    return build_tagging_function(
        tags,
        instructions,
    )