set -e

cd ../klee
rm -rf build
mkdir build
cd build

Z3_INCLUDE_DIRS="TODO:"
Z3_LIBRARIES="TODO:"
KLEE_UCLIBC_PATH="TODO:"
LLVM_CONFIG_BINARY="TODO:"

cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_SEMANTIC=ON -DENABLE_SEMANTIC=ON -DENABLE_SOLVER_Z3=ON -DZ3_INCLUDE_DIRS=$Z3_INCLUDE_DIRS -DZ3_LIBRARIES=$Z3_LIBRARIES -DENABLE_POSIX_RUNTIME=ON -DKLEE_UCLIBC_PATH=$KLEE_UCLIBC_PATH -DLLVM_CONFIG_BINARY=$LLVM_CONFIG_BINARY ..
make -j4
echo "KLEE build done."
